Repository pagopa/pagopa-payment-wallet-scheduler-service, pull requests merged in 2024-10, with the labels that each got.

#1 [CHK-3505] feat: repo initial setup
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  .gitignore
  .java-version
  .pre-commit-config.yaml
  CODEOWNERS
  HELP.md
  README.md
  build.gradle.kts
  eclipse-style.xml
  gradle.lockfile
  gradle.propetries
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerServiceApplication.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
  src/test/kotlin/it/pagopa/wallet/scheduler/SchedulerApplicationTests.kt
Labels: skip-release

#3 [CHK-3506] feat: setup local env
  .env.local
  Dockerfile
  README.md
  build.gradle.kts
  docker-compose.yml
  docker-local/azurite/Dockerfile
  docker-local/azurite/create-queues.sh
  docker-local/mongo/mongo-express.env
  docker-local/mongo/mongodb.env
  gradle/verification-metadata.xml
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/SchedulerApplicationTests.kt
  src/test/resources/application-test.properties
Labels: chart-minor, minor

#2 [CHK-3508] chore(deploy): add deploy config
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .env.local
  build.gradle.kts
  gradle/verification-metadata.xml
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/resources/application.properties
Labels: chart-minor, minor, size/large

#5 [CHK-3510] feat(producer): add producer service
  .env.local
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/cdc/AuditWallet.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/cdc/AuditWalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/cdc/AuditWalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/cdc/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/queue/CdcQueueEvent.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/queue/TracingInfo.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/serialization/LoggingEventMixin.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/tracing/TracingUtils.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/AzureStorageConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/OpenTelemetryConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/CdcQueueConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/RetrySendPolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/service/CdcEventDispatcherService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/common/serialization/LoggingEventMixinTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/service/CdcEventDispatcherServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/util/TracingUtilsTest.kt
  src/test/resources/WalletDeletedEvent.json
  src/test/resources/WalletOnboardCompletedEventCards.json
  src/test/resources/WalletOnboardCompletedEventPayPal.json
  src/test/resources/application-test.properties
Labels: chart-minor, minor, size/large
