Repository pagopa/pagopa-payment-wallet-scheduler-service, pull requests merged in 2024-11, with the labels that each got.

#7 Feat [CHK-3511] Adding checkpointing service logic and configuration
  .env.local
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata_.xml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/RedisConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/RedisResumePolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/service/RedisResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/service/ResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/service/TimestampRedisTemplate.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/service/RedisResumePolicyServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/service/TimeStampRedisTemplateTest.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small

#4 [CHK-3509] feat: add service to retrieve wallets based on search criteria
  .env.local
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata_.xml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Client.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/PayPalDetails.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/MongoConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/WalletSearchConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/exceptions/WalletInvalidRangeException.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/service/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/utils/InstantConverters.kt
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/config/WalletSearchConfigTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/documents/WalletDocumentTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/repositories/WalletRepositoryTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small

#6 Chk 3529 job logic implementation
  README.md
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/PagopaPaymentWalletSchedulerServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/common/cdc/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/AzureStorageConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/PaymentWalletJobConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/exceptions/NoWalletFoundException.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/jobs/ScheduledJob.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/jobs/config/JobConfigurations.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/jobs/paymentwallet/OnboardedPaymentWalletJob.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/scheduledjob/PaymentWalletScheduledJob.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/CdcEventDispatcherService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/RedisResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/ResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/TimestampRedisTemplate.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/documents/WalletDocumentTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/jobs/paymentwallet/OnboardedPaymentWalletJobTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/repositories/WalletRepositoryTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/scheduledjob/PaymentWalletScheduledJobTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/CdcEventDispatcherServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/RedisResumePolicyServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/TimeStampRedisTemplateTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor

#8 Feat [CHK-3522] Added integration test in code review pipeline
  .devops/code-review-pipelines.yml
  .env.local
  docker-compose.yml
  docker-local/azurite/Dockerfile
  docker-local/azurite/create-queues.sh
  docker-local/mongo/mongo-express.env
  docker-local/mongo/mongo-init.js
  docker-local/mongo/mongodb.env
  integration-test/onboarding-wallet-card.json
  integration-test/onboarding-wallet-paypal.json
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small

#10 [CHK-3538] feat(checkpoint): add checkpoint to payment wallet job
  .env.local
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/scheduler/jobs/paymentwallet/OnboardedPaymentWalletJob.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/RedisResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/ResumePolicyService.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/TimestampRedisTemplate.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/jobs/paymentwallet/OnboardedPaymentWalletJobTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/RedisResumePolicyServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/TimeStampRedisTemplateTest.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small

#11 [CHK-3539] feat: add job lock integration
  src/main/kotlin/it/pagopa/wallet/scheduler/scheduledjob/PaymentWalletScheduledJob.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/scheduledjob/PaymentWalletScheduledJobTest.kt
Labels: chart-minor, minor, size/small

#13 [CHK-3545] feat(semaphore): change redis wait time from seconds to milliseconds
  .env.local
  README.md
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/RedisJobLockPolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/SchedulerLockService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/config/WalletSchedulerConfigsTest.kt
  src/test/kotlin/it/pagopa/wallet/scheduler/services/SchedulerLockServiceTest.kt
  src/test/resources/application.test.properties
Labels: chart-patch, patch, size/small

#14 [CHK-3545] feat(semaphore): change redis ttl from seconds to milliseconds
  .env.local
  README.md
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/scheduler/config/properties/RedisJobLockPolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/scheduler/services/SchedulerLockService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/scheduler/config/WalletSchedulerConfigsTest.kt
  src/test/resources/application.test.properties
Labels: chart-patch, patch, size/small
